// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniSystem.Infrastructure;

#nullable disable

namespace UniSystem.Infrastructure.Migrations
{
    [DbContext(typeof(UniSystemDbContext))]
    partial class UniSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniSystem.Domain.Entities.AcademicGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Course")
                        .HasColumnType("smallint")
                        .HasColumnName("course");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer")
                        .HasColumnName("specialty_id");

                    b.HasKey("Id")
                        .HasName("pk_academic_groups");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_academic_groups_name");

                    b.HasIndex("SpecialtyId")
                        .HasDatabaseName("ix_academic_groups_specialty_id");

                    b.ToTable("academic_groups", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeanCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dean_check_at");

                    b.Property<int>("DocumentCurrentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("document_current_status_id");

                    b.Property<int?>("DocumentDeanStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("document_dean_status_id");

                    b.Property<int?>("DocumentSecretaryStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("document_secretary_status_id");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("document_type_id");

                    b.Property<string>("DynamicValues")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("dynamic_values");

                    b.Property<string>("ResolutionComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_comment");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<DateTimeOffset?>("SecretaryCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("secretary_check_at");

                    b.Property<DateTimeOffset?>("SendToReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("send_to_review_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("DocumentCurrentStatusId")
                        .HasDatabaseName("ix_documents_document_current_status_id");

                    b.HasIndex("DocumentDeanStatusId")
                        .HasDatabaseName("ix_documents_document_dean_status_id");

                    b.HasIndex("DocumentSecretaryStatusId")
                        .HasDatabaseName("ix_documents_document_secretary_status_id");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_documents_document_type_id");

                    b.HasIndex("ResolvedByUserId")
                        .HasDatabaseName("ix_documents_resolved_by_user_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_documents_student_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.DocumentAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_document_attachments");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_attachments_document_id");

                    b.ToTable("document_attachments", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.DocumentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_document_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_document_statuses_name");

                    b.ToTable("document_statuses", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresAttachments")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_attachments");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_text");

                    b.HasKey("Id")
                        .HasName("pk_document_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_document_types_name");

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameDative")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_dative");

                    b.Property<string>("NameNominative")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_nominative");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("SystemName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_system_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<short>("MaxDurationInYears")
                        .HasColumnType("smallint")
                        .HasColumnName("max_duration_in_years");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_specialties");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_specialties_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_specialties_name");

                    b.ToTable("specialties", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AcademicGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_group_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_staff_profiles");

                    b.HasIndex("AcademicGroupId")
                        .HasDatabaseName("ix_staff_profiles_academic_group_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_staff_profiles_department_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_profiles_user_id");

                    b.ToTable("staff_profiles", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.StaffSubject", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.HasKey("StaffId", "SubjectId")
                        .HasName("pk_staff_subjects");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_staff_subjects_subject_id");

                    b.ToTable("staff_subjects", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcademicGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_group_id");

                    b.Property<int>("StudentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("student_status_id");

                    b.Property<string>("StudentTicket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_ticket");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student_profiles");

                    b.HasIndex("AcademicGroupId")
                        .HasDatabaseName("ix_student_profiles_academic_group_id");

                    b.HasIndex("StudentStatusId")
                        .HasDatabaseName("ix_student_profiles_student_status_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_user_id");

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.StudentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_student_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_student_statuses_name");

                    b.ToTable("student_statuses", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_name");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_path");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.AcademicGroup", b =>
                {
                    b.HasOne("UniSystem.Domain.Entities.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academic_groups_specialties_specialty_id");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.Document", b =>
                {
                    b.HasOne("UniSystem.Domain.Entities.DocumentStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("DocumentCurrentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_document_statuses_document_current_status_id");

                    b.HasOne("UniSystem.Domain.Entities.DocumentStatus", "DeanStatus")
                        .WithMany()
                        .HasForeignKey("DocumentDeanStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documents_document_statuses_document_dean_status_id");

                    b.HasOne("UniSystem.Domain.Entities.DocumentStatus", "SecretaryStatus")
                        .WithMany()
                        .HasForeignKey("DocumentSecretaryStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documents_document_statuses_document_secretary_status_id");

                    b.HasOne("UniSystem.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_document_types_document_type_id");

                    b.HasOne("UniSystem.Domain.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documents_users_resolved_by_user_id");

                    b.HasOne("UniSystem.Domain.Entities.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_student_profiles_student_id");

                    b.Navigation("CurrentStatus");

                    b.Navigation("DeanStatus");

                    b.Navigation("DocumentType");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("SecretaryStatus");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.DocumentAttachment", b =>
                {
                    b.HasOne("UniSystem.Domain.Entities.Document", "Document")
                        .WithMany("Attachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_attachments_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.StaffProfile", b =>
                {
                    b.HasOne("UniSystem.Domain.Entities.AcademicGroup", "AcademicGroup")
                        .WithMany()
                        .HasForeignKey("AcademicGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_staff_profiles_academic_groups_academic_group_id");

                    b.HasOne("UniSystem.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_profiles_departments_department_id");

                    b.HasOne("UniSystem.Domain.Entities.User", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("UniSystem.Domain.Entities.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_profiles_users_user_id");

                    b.Navigation("AcademicGroup");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.StaffSubject", b =>
                {
                    b.HasOne("UniSystem.Domain.Entities.StaffProfile", "StaffProfile")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_subjects_staff_profiles_staff_id");

                    b.HasOne("UniSystem.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_subjects_subjects_subject_id");

                    b.Navigation("StaffProfile");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("UniSystem.Domain.Entities.AcademicGroup", "AcademicGroup")
                        .WithMany("Students")
                        .HasForeignKey("AcademicGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_academic_groups_academic_group_id");

                    b.HasOne("UniSystem.Domain.Entities.StudentStatus", "StudentStatus")
                        .WithMany()
                        .HasForeignKey("StudentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_student_statuses_student_status_id");

                    b.HasOne("UniSystem.Domain.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("UniSystem.Domain.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_users_user_id");

                    b.Navigation("AcademicGroup");

                    b.Navigation("StudentStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("UniSystem.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.AcademicGroup", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.Document", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("UniSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("StaffProfile");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
